name: Major Productions
favicon: null
layout_spectrum: 0.25818
typography_spectrum: 0.49086
title: '2015 '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#36bfbb'
    - '#030303'
    - '#dd706a'
    - '#fe0303'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
